data:
  name: mnist
  path: data/datasets/mnist_subset_10_per_class.pth
  num_classes: 10
  num_samples: 100
divide_run: 1
input_ball:
  epsilon: 0.026
  norm: Linf
network:
  name: 9x100
  path: data/models/mnist_adv_9x100.pt
  K: 10
  n:
  - 784
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 10
models:
- certification_model_type: TargetedSDP
  solver: mosek_classic
  cuts:
  - RLT
  - triangularization
  RLT_props:
  - 1.0
  all_combinations_cuts: false
  CHORDAL_DECOMPOSITION: true
  LAST_LAYER: false
  use_callback: false
  use_active_neurons: true
  use_inactive_neurons: false
  keep_penultimate_actives: true
  bounds_method: from_file
  bounds_file: data/bounds/9x100-0.026_linf.csv
  solver_time_limit: 60
  dynamic_conic_bundle:
    enabled: true
    dualize:
    - RLT
    engine: conicbundle_native
    max_iter: 60
    term_relprec: 1.0e-07
    log_every: 5
    print_level: 0
    eval_limit: 400
    print_png: false
    factor: 0.01
  use_compact_add_rlt: true
